/**
 * The app→PostHog join key, pinned.
 *
 * Every vector below was generated by running the APP's own pseudoId (src/analytics.ts) — not by
 * running the copy under test, which would only prove it agrees with itself. If these ever fail,
 * the two implementations have drifted and every per-user timeline in the admin panel is silently
 * empty: a wrong id does not error, it just matches nobody, and the panel reads as "this user did
 * nothing" for every single user.
 *
 * Run: node app/lib/pseudoId.test.mjs
 */
import { pseudoId } from "./pseudoId.js";

let pass = 0, fail = 0;
const eq = (got, want, msg) => {
  if (got === want) pass++;
  else { fail++; console.error(`  FAIL ${msg}\n    got:  ${got}\n    want: ${want}`); }
};

eq(pseudoId("+919911108870"), "u_72c7c35804feadb6", "full E.164 number");
eq(pseudoId("+917995658986"), "u_8aa4525452c8601a", "a second real number");
eq(pseudoId("+911234567890"), "u_0b482d23e5f02753", "an arbitrary number");
eq(pseudoId("919990108870"),  "u_a7fbe1777367d95b", "no plus prefix");

// Normalisation is part of the contract, not a detail: the admin list stores +91 99111 08870 while
// the app may have seen 9911108870. If only the hash matched and not the normalisation, the same
// human would resolve to three different ids depending on which screen wrote the number down.
const canonical = "u_72c7c35804feadb6";
eq(pseudoId("9911108870"), canonical, "bare 10 digits match the E.164 form");
eq(pseudoId("+91 99111 08870"), canonical, "spaces are stripped");
eq(pseudoId("+91-99111-08870"), canonical, "dashes are stripped");
eq(pseudoId("0919911108870"), canonical, "a longer prefix still resolves on the last 10 digits");

// Degenerate input must not throw — the admin list contains rows with no phone number at all.
eq(pseudoId(""), "u_0c6dfe42aeb575c6", "empty string is stable, not a crash");
eq(pseudoId(null), pseudoId(""), "null behaves as empty");
eq(pseudoId(undefined), pseudoId(""), "undefined behaves as empty");

// Different people must not collide on the prefix.
if (pseudoId("+919911108870") === pseudoId("+917995658986")) { fail++; console.error("  FAIL distinct numbers collide"); }
else pass++;

console.log(`  ${pass}/${pass + fail} pseudoId checks passed`);
if (fail) process.exit(1);
