import LegalHeader from "../components/LegalHeader";
import Footer from "../components/Footer";
import { Arrow } from "../components/Icons";

export const metadata = {
  title: "Privacy Policy — Tring",
  description: "How Tring (Mavrix AI Private Limited) collects, uses, and protects your information.",
  alternates: { canonical: "https://heytring.com/privacy" },
};

export default function Privacy() {
  return (
    <>
      <LegalHeader />
      <main className="legal">
        <div className="legal__wrap">
          <a className="back" href="/"><Arrow style={{ transform: "rotate(180deg)" }} /> Home</a>
          <h1>Privacy Policy</h1>
          <p className="updated">Last updated: 13 July 2026</p>

          <p style={{ marginTop: 24 }}>
            This privacy notice for <strong>Mavrix AI Private Limited</strong> (CIN{" "}
            <strong>U62099KA2025PTC210316</strong>), registered at{" "}
            <strong>No. 8/3, Prince Ville, Challaghatta Village, Domlur, Bangalore North,
            Bangalore – 560071, Karnataka, India</strong> (operator of <strong>Tring</strong>;
            &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) describes how and why we
            collect, store, use, and/or share (&ldquo;process&rdquo;) your information when you
            use our services (&ldquo;Services&rdquo;), such as when you:
          </p>
          <ul>
            <li>Visit our website at <a href="https://heytring.com">https://heytring.com</a>, or any website of ours that links to this privacy notice</li>
            <li>Use our mobile application (<strong>&ldquo;Tring&rdquo;</strong> or the &ldquo;App&rdquo;), whose AI assistant is named <strong>Ring</strong></li>
            <li>Engage with us in other related ways — including when Ring answers calls diverted to you, or places calls on your behalf</li>
          </ul>
          <p>
            <strong>Questions or concerns?</strong> Reading this privacy notice will help you
            understand your privacy rights and choices. If you do not agree with our policies
            and practices, please do not use our Services. If you still have questions, contact
            us at <a href="mailto:customer@heytring.com">customer@heytring.com</a> or by post at
            Mavrix AI Private Limited, No. 8/3, Prince Ville, Challaghatta Village, Domlur,
            Bangalore North, Bangalore – 560071, Karnataka, India.
          </p>

          <h2>Summary of key points</h2>
          <ul>
            <li><strong>The Services are offered to users located in India</strong> and comply with the applicable Indian data-protection laws in effect at the time of offering, including the Information Technology Act, 2000 and the Digital Personal Data Protection Act, 2023.</li>
            <li><strong>What we process:</strong> account details, the calls Ring handles for you (recordings, transcripts, summaries), your synced contact names (with permission), and — only if you turn it on — a voice sample for voice cloning.</li>
            <li><strong>Everything is encrypted</strong> in transit (HTTPS/TLS) and at rest; transcripts are additionally encrypted per user.</li>
            <li><strong>We never sell your data</strong>, never use it for advertising, and <strong>never use your voice or call audio to train any AI model.</strong></li>
            <li><strong>Your human-to-human calls are never stored:</strong> the moment you take over a call, recording and transcription stop.</li>
            <li><strong>Third-party AI providers</strong> (e.g. OpenAI, Anthropic, Google) process the minimum data needed to run your assistant, under contracts that forbid onward sharing and model-training on your data.</li>
            <li><strong>You are in control:</strong> pause screening anytime, delete any call, or delete your whole account and all associated data.</li>
          </ul>

          <h2>1. What information do we collect?</h2>
          <p>We collect personal information that you provide to us and information generated when Ring handles calls for you.</p>
          <h3>Information you provide</h3>
          <ul>
            <li>Name, phone number, and chosen assistant language</li>
            <li>Synced contact names and numbers — <strong>only if</strong> you grant Contacts permission</li>
            <li>A short voice sample — <strong>only if</strong> you enable voice cloning</li>
            <li>Task instructions and any details you give Ring to complete an errand</li>
            <li>Anything you share when you contact support</li>
          </ul>
          <h3>Information generated by the Service</h3>
          <ul>
            <li><strong>Call recordings and transcripts of the AI portion of calls</strong> Ring handles</li>
            <li>Call records — caller number/name, time, duration, and outcome</li>
            <li>Call notes and summaries generated from the transcript</li>
            <li>Favourites and screening preferences</li>
            <li>Device push identifiers (to deliver call notifications)</li>
            <li>Usage/log data — app activity, device type, OS, IP address — for reliability and security</li>
          </ul>
          <div className="callout">
            <p><strong>Payment data.</strong> If you buy a paid feature, payment is processed by Razorpay / Google Play / Apple. Card and payment-instrument details are handled and stored by those processors — <strong>they never touch our servers.</strong></p>
          </div>
          <p><strong>Sensitive information.</strong> We do not seek sensitive personal information. If a task you ask Ring to perform requires it, we process it only with your explicit, in-context consent.</p>
          <p><strong>Children.</strong> The Services are for users <strong>18 or older</strong>. We do not knowingly collect data from minors; if we learn we have, we deactivate the account and delete the data.</p>

          <h2>2. How do we process your information?</h2>
          <p>We process your information to:</p>
          <ul>
            <li>create and authenticate your account and route your calls;</li>
            <li>have Ring screen inbound calls and run outbound errands you request — including sending the relevant call content to third-party AI providers to generate responses, transcripts, and summaries (see §4);</li>
            <li>show you your live call view, notifications, and call history;</li>
            <li>respond to support requests and send you administrative messages;</li>
            <li>maintain security, prevent fraud/abuse, and debug errors;</li>
            <li>comply with law.</li>
          </ul>
          <p>We process your information only where we have a valid legal basis to do so, primarily <strong>your consent</strong> and the <strong>performance of our service to you.</strong></p>

          <h2>3. What we store — and what we do NOT store</h2>
          <h3>Stored (encrypted in transit and at rest)</h3>
          <table>
            <thead>
              <tr><th>Data</th><th>Why</th><th>How long</th></tr>
            </thead>
            <tbody>
              <tr><td>Account info — name, phone number, assistant language</td><td>run your account, route calls</td><td>while your account is active</td></tr>
              <tr><td>Call records — caller number/name, time, duration, outcome</td><td>your call history</td><td>while your account is active</td></tr>
              <tr><td>Recordings &amp; transcripts of the <strong>AI portion</strong> of calls</td><td>replay/read what Ring handled; generate your note</td><td>while your account is active</td></tr>
              <tr><td>Call notes / summaries</td><td>the &ldquo;what happened&rdquo; card</td><td>while your account is active</td></tr>
              <tr><td>Synced contact names (with Contacts permission)</td><td>show names instead of numbers</td><td>current copy only — old copies not kept</td></tr>
              <tr><td>Favourites &amp; screening preferences</td><td>important people always reach you</td><td>while your account is active</td></tr>
              <tr><td>Device push identifiers</td><td>deliver notifications</td><td>until logout / account deletion</td></tr>
              <tr><td>Voice sample (<strong>only if voice cloning is on</strong>)</td><td>let Ring speak in a voice like yours</td><td>encrypted; deleted when you disable it or delete your account</td></tr>
            </tbody>
          </table>
          <p>Transcripts are additionally encrypted <strong>per user</strong> — only your authenticated session can decrypt them.</p>
          <h3>NOT stored</h3>
          <ul>
            <li><strong>Your human-to-human conversations.</strong> When you take over a call, recording and transcription stop at hand-over. What you say to the caller yourself is never recorded, transcribed, or stored — only the AI portion is kept.</li>
            <li><strong>Your voice or call audio for training</strong> any AI model (see §5).</li>
            <li><strong>Historical copies of your contacts</strong> — only the current synced copy exists.</li>
            <li><strong>Your location</strong> — if granted, it is used on-device only to make notifications relevant; never used to track you; the app works fully without it.</li>
            <li><strong>Payment card details</strong> — handled entirely by Razorpay / Google Play / Apple.</li>
            <li>We <strong>never sell your personal information</strong> and <strong>never publish your calls.</strong></li>
          </ul>

          <h2>4. AI features and third-party AI providers</h2>
          <p>Ring is powered by third-party AI model providers (&ldquo;AI Service Providers&rdquo;), which may include <strong>OpenAI, Anthropic, Google</strong>, and other model providers, selected per task on a best-effort basis for quality and speed.</p>
          <p><strong>What is sent to AI providers:</strong> the call transcript/content and task context needed to generate a response, transcript, or summary; your name/contact details only when essential to complete a task (e.g. making a booking for you).</p>
          <p><strong>What is NOT sent:</strong> your payment information, your login credentials, your voice sample for model training, and any data unrelated to the task.</p>
          <p><strong>Safeguards.</strong> Our contracts require AI providers to (a) keep your data confidential, (b) use it only to perform your task, (c) <strong>not train their models on your data</strong>, and (d) delete it on our request. We do not sell your data or use it for advertising.</p>
          <p><strong>Your consent and control.</strong> By submitting tasks you consent to this task-scoped sharing. You can withdraw AI-processing consent anytime from your profile; because the assistant relies on AI to function, withdrawing consent has the same practical effect as deleting your account.</p>

          <h2 id="voice">5. Voice cloning — how your voice sample is used</h2>
          <p>Tring offers <strong>instant voice cloning</strong> so Ring can answer in a voice like yours.</p>
          <ul>
            <li><strong>Instant (zero-shot) cloning only.</strong> Your short voice sample conditions an <strong>existing, pre-trained</strong> speech model at the moment speech is generated. Nothing is trained.</li>
            <li><strong>We never train on your voice.</strong> Your voice sample and call audio are <strong>never</strong> used to train, fine-tune, or update any AI model — ours or a third party&rsquo;s. Remove your sample and nothing of it remains in any model.</li>
            <li><strong>Stored encrypted, used only for you,</strong> and permanently deleted when you disable the feature or delete your account.</li>
            <li><strong>Only your own voice,</strong> with your in-app consent. Cloning any other person&rsquo;s voice is prohibited. We never build voice profiles of your callers.</li>
          </ul>

          <h2>6. How long do we keep your information?</h2>
          <p>We keep your information only as long as needed to provide the Services — generally while your account is active — unless a longer period is required or permitted by law (e.g. tax or accounting). When there is no ongoing need, we delete or anonymise it, or isolate it from further processing until deletion is possible.</p>

          <h2>7. How do we keep your information safe?</h2>
          <p>We use appropriate technical and organisational measures — encryption in transit and at rest, per-user transcript encryption, isolated per-user storage, and server-side key management with periodic rotation. No method of transmission or storage is 100% secure, so we cannot guarantee absolute security; you access the Services at your own risk.</p>

          <h2 id="recording">8. Call-recording notice</h2>
          <p>Calls handled by Ring are recorded and transcribed so you get your note and history. Depending on the caller&rsquo;s jurisdiction we may be unable to directly notify every third-party caller that an AI is handling or recording the call; by using Tring you acknowledge this and remain responsible for compliance with the laws applicable to your own use.</p>

          <h2 id="rights">9. Your rights and how to exercise them</h2>
          <p>You may request to access, correct, or delete your personal information, and withdraw consent, subject to applicable law. To do so, email <a href="mailto:customer@heytring.com">customer@heytring.com</a> or use the in-app controls.</p>
          <ul>
            <li><strong>Pause anytime</strong> — turn screening off in the app or dial your carrier&rsquo;s deactivation code; calls then ring your phone directly.</li>
            <li><strong>Delete a call</strong> — any recording/transcript/note can be deleted from your history.</li>
            <li><strong>Delete your account</strong> — Settings → Delete account. We delete your account and all associated personal data, remove the mapping between your identity and your call/task data, and instruct our AI providers to delete any retained data, <strong>within 30 days</strong> — except the minimum we must keep for legal obligations (access-restricted).</li>
          </ul>

          <h2>10. Updates to this notice</h2>
          <p>We may update this notice to stay compliant with relevant laws. The &ldquo;Last updated&rdquo; date above will change, and material changes will be notified in-app or by email to the address you registered with.</p>

          <h2>11. Contact</h2>
          <p>
            <strong>Mavrix AI Private Limited</strong> (CIN U62099KA2025PTC210316)<br />
            No. 8/3, Prince Ville, Challaghatta Village, Domlur, Bangalore North,<br />
            Bangalore – 560071, Karnataka, India<br />
            <a href="mailto:customer@heytring.com">customer@heytring.com</a> — <a href="https://heytring.com">https://heytring.com</a>
          </p>
          <p>Grievances are acknowledged within 24 hours and resolved within the timelines of the Information Technology Act, 2000 and the DPDP Act, 2023.</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
